# 默认允许主世界猪人塔
disableWorlds:
  - world_the_nether
  - world_the_end
# 猪人塔区块的 X Z 坐标
# 格式: WorldName ChunkLocationX ChunkLocationZ
# 使用指令 /pigman setChunk 设置脚下区块为猪人塔区块
pigManChunkLists:
  - world 100 100
  - world 1 1
# 猪人堆叠位置的 X Y Z 坐标
# 格式 WorldName BlockLocationX BlockLocationY BlockLocationZ
# 使用指令 /pigman setBlock <X> <Y> <Z> 设置指定方块为猪人堆叠位置（在此方块位置周围3*4*3的生物将会被取消AI）
# 不止限于猪人的优化 有生物密集堆叠的位置都可以加以设置
pigManBlockLists:
  - world 0 80 0
# 每个区块(16x16)的*总生物*数量限制
perChunkLimit: 50
# 每个世界的猪人限制
perWorldPigManLimit: 200